version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./web:/app
    restart: unless-stopped
    command: pm2 serve dist -p 3000 ---spa
    ports:
      - 3000:3000
